# Configurations
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: pygments
=======
name: Alex Johnson
description:  MSI, Digital Initiatives + Library Technology Professional Seeking Full-Time Employment

# Permalinks
permalink:        /blog/:year/:month/:day/:title

# Setup
title:            'Alex Johnson'
tagline:          'MSI, Digital Initiatives/Library Technology Professional Seeking Full-Time Employment'
description:      'digital initiatives + access + web + code == career wrangling'
url:              'ahjohns.github.io'
baseurl:          ''


# Navigation
navigation:
- text: About
  url: /about/
- text: Resume
  url: /resume/AlexandraJohnson'sResume3.pdf
- text: Blog
  url: /blog/
- text: Tags
  url: /tags/
- text: Archive
  url : /archive/
=======
url: https://ahjohns.github.io
permalink: /:year/:month/:title/
owner:
    name: Alex Johnson # 
    twitter: atothejo 
    github: ahjohns 
    disqus_shortname: #
    email: ahjohns@umich.edu
    facebook: atothejo




# Author Details
author:         'Alex Johnson'

#Social Media links
linkedin:       'https://www.linkedin.com/profile/preview?locale=en_US&trk=prof-0-sb-preview-primary-button'
twitter:        'https://twitter.com/atoejo'
facebook:       'https://www.facebook.com/atothejo'
gplus:          'https://plus.google.com/u/0/117169558039298133147/posts'

# Google Analytics
gahandler: 'UA-64089707-1'

#if footer-links-visible is 'true' the svg-icons will be shown top on the copy right.
#else the svg icons will not exist
footersvg: 'true'

footer-links:
  dribbble:
  email: 'ahjohns@umich.edu'
  facebook:
  flickr:
  github: 'ahjohns.github.com'
  instagram:
  linkedin: 'https://www.linkedin.com/profile/preview?locale=en_US&trk=prof-0-sb-preview-primary-button'
  pinterest:
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  google: None
  twitter: atotejo
  stackoverflow: #users/4388898/peter-zhu # your stackoverflow profile, e.g. "users/50476/bart-kiers"

# Disqus
disqushandler: 'testingblogo'

# Blog Configurations
paginate: 10 # Posts per page on the blog index
paginate_path: '/blog/page:num'
destination: ./_site

# Custom vars
version:          0.8
=======
timezone: Detroit
>>>>>>> origin/master
