name: Alex Johnson
description:  MSI, Digital Initiatives + Library Technology Professional Seeking Full-Time Employment

sass:
  sass_dir: assets/css/_sass
  style: :compressed

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "tables", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

url: https://ahjohns.github.io
permalink: /:year/:month/:title/
owner:
    name: Alex Johnson # 
    twitter: atothejo 
    github: ahjohns 
    disqus_shortname: #
    email: ahjohns@umich.edu
    facebook: atothejo

ga_id: #
ga_username: #

timezone: Detroit
